### ISSUE TITLE
fix(collection): adjust Dark collection style to meet expectations

### ISSUE THREAD

**Issue by mathetos** [WordImpress/wp-business-reviews#150]
Currently when the "Seamless Dark" theme is selected for a Collection, it displays perfectly in the admin:
![image](https://user-images.githubusercontent.com/930724/40943905-a94dcb5c-6807-11e8-9a51-d11adae8e7d1.png)

But not on the front-end:
![image](https://user-images.githubusercontent.com/930724/40943917-b81b19e6-6807-11e8-95f4-2abc8f0c297f.png)

It affects both the "List" and "Gallery" display options.

**Comment by kevinwhoffman** [comment]
This is the intended behavior, as Seamless Dark is meant to display reviews seamlessly within a WordPress theme that is already dark.

In the Builder, the background changes so you can preview what it looks like on a dark background. But on the front end, it doesn't actually change the background of the page; it just flips the text color so that text is legible on a dark background styled by the WordPress theme.

With that said, we need to clarify what it's intended for if your expectation was that it creates a dark container.

**Comment by mathetos** [comment]
Hmmm... I see what you mean, but I think we'd be a lot safer if we made sure that the themes actually looked exactly as they look in the backend explicitly. Use your CSS-specificity awesomeness there ;-)
